### ISSUE TITLE
RuntimeError with ResNetUNet

### ISSUE THREAD

**Issue by prarobinson** [usuyama/pytorch-unet#12]
Hello!

When I get to the line 

>>>model = ResNetUNet(6)

I receive the following error message:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __init__
  File "/home/paulr/Programming/anaconda3/lib/python3.7/site-packages/torchvision/models/resnet.py", line 237, in resnet18
    **kwargs)
  File "/home/paulr/Programming/anaconda3/lib/python3.7/site-packages/torchvision/models/resnet.py", line 220, in _resnet
    model = ResNet(block, layers, **kwargs)
  File "/home/paulr/Programming/anaconda3/lib/python3.7/site-packages/torchvision/models/resnet.py", line 142, in __init__
    bias=False)
  File "/home/paulr/Programming/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 332, in __init__
    False, _pair(0), groups, bias, padding_mode)
  File "/home/paulr/Programming/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 46, in __init__
    self.reset_parameters()
  File "/home/paulr/Programming/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 49, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/home/paulr/Programming/anaconda3/lib/python3.7/site-packages/torch/nn/init.py", line 315, in kaiming_uniform_
    return tensor.uniform_(-bound, bound)
RuntimeError: a leaf Variable that requires grad has been used in an in-place operation.

This looks likeit might be a bug in pytorch (or maybe just how I'm using it), but if you have any pointers I'd be greatful.

Thanks,
P

**Comment by usuyama** [comment]
Hi @prarobinson thanks for trying this repo. 
Which version of PyTorch are you using? I created this repo with PyTorch 0.4.1 so there might be some breaking changes with new versions.

**Comment by prarobinson** [comment]
Thanks for getting back to me. I am using a newer version of PyTorch, but
what is most puzzling is that the notebook seems to execute fine locally,
but when I run it at the command line I get the error I mentioned. I didn't
see that the notebook used any special environment. I can try to rollback
to 0.4.1, but was hoping you might have an idea of where in the code the
in-line replacement is happening; I have a suspicion that this could be a
quick fix, but I'm pretty new to PyTorch.

Thanks,
Paul

**Comment by usuyama** [comment]
Hmm that's interesting. Can you try to repro on an online notebook and share? e.g. https://colab.research.google.com/
